name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - github-test  # Trigger when pushing to main

permissions:
  contents: write  # âœ… Allow the workflow to push changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href ./

      - name: Move build output to docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -r dist/made3-d/browser/* docs/

      - name: Add CNAME for custom domain
        run: echo "made3D.tn" > docs/CNAME

      - name: Commit & push deployment
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy new build [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Elyes853/made-3D.git HEAD:main
